/*
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nvt.api.client.api;

import com.nvt.api.client.*;
import com.nvt.api.client.auth.*;
import com.nvt.api.client.model.SmsSendRequest;
import com.nvt.api.client.model.SmsSendResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Send a text message request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsSendTest() throws ApiException {
        //SmsSendRequest smsSendRequest = null;
        //SmsSendResponse response = api.smsSend(smsSendRequest);
        // TODO: test validations
    }

}
